CREATE TABLE IF NOT EXISTS iam_user (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    legacy_id VARCHAR(32),
    username VARCHAR(64) NOT NULL,
    nickname VARCHAR(64) NOT NULL,
    password VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL DEFAULT '',
    phone VARCHAR(32) NOT NULL DEFAULT '',
    avatar VARCHAR(512) NOT NULL DEFAULT '',
    remarks VARCHAR(512) NOT NULL DEFAULT '',
    status SMALLINT NOT NULL DEFAULT 1,
    mfa_enabled BOOLEAN NOT NULL DEFAULT FALSE,
    mfa_secret VARCHAR(512) NOT NULL DEFAULT '',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    deleted_at TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS cluster (
    id VARCHAR(32) PRIMARY KEY,
    name VARCHAR(128) NOT NULL,
    api_endpoint VARCHAR(255) NOT NULL,
    upstream_bearer_token TEXT,
    ca_cert_pem TEXT,
    tls_server_name VARCHAR(255),
    skip_tls_verify BOOLEAN NOT NULL DEFAULT FALSE,
    "default" BOOLEAN NOT NULL DEFAULT FALSE,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    deleted_at TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS iam_auth_session (
    id VARCHAR(64) PRIMARY KEY,
    subject VARCHAR(128) NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    revoked_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS iam_revoked_token (
    id VARCHAR(64) PRIMARY KEY,
    expires_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS iam_refresh_token (
    id VARCHAR(64) PRIMARY KEY,
    session_id VARCHAR(64) NOT NULL,
    subject VARCHAR(128) NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    revoked_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS iam_login_failure (
    key VARCHAR(256) PRIMARY KEY,
    count INTEGER NOT NULL,
    locked_until TIMESTAMPTZ NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS iam_captcha_challenge (
    id VARCHAR(128) PRIMARY KEY,
    digits BYTEA NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS iam_oidc_state (
    state VARCHAR(128) PRIMARY KEY,
    expires_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS iam_external_identity (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    provider VARCHAR(255) NOT NULL,
    subject VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL DEFAULT '',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_iam_external_identity_user
        FOREIGN KEY (user_id) REFERENCES iam_user(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_iam_user_deleted_at
    ON iam_user (deleted_at);

CREATE UNIQUE INDEX IF NOT EXISTS idx_iam_user_legacy_id_active
    ON iam_user (legacy_id)
    WHERE deleted_at IS NULL AND legacy_id IS NOT NULL AND legacy_id <> '';

CREATE UNIQUE INDEX IF NOT EXISTS idx_iam_user_username_active
    ON iam_user (username)
    WHERE deleted_at IS NULL;

CREATE UNIQUE INDEX IF NOT EXISTS idx_iam_user_email_active
    ON iam_user (email)
    WHERE deleted_at IS NULL AND email <> '';

CREATE INDEX IF NOT EXISTS idx_cluster_deleted_at
    ON cluster (deleted_at);

CREATE UNIQUE INDEX IF NOT EXISTS idx_cluster_default_true
    ON cluster ("default")
    WHERE "default" = TRUE AND deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS idx_iam_auth_session_subject
    ON iam_auth_session (subject);

CREATE INDEX IF NOT EXISTS idx_iam_auth_session_expires_at
    ON iam_auth_session (expires_at);

CREATE INDEX IF NOT EXISTS idx_iam_auth_session_revoked_at
    ON iam_auth_session (revoked_at);

CREATE INDEX IF NOT EXISTS idx_iam_revoked_token_expires_at
    ON iam_revoked_token (expires_at);

CREATE INDEX IF NOT EXISTS idx_iam_refresh_token_session_id
    ON iam_refresh_token (session_id);

CREATE INDEX IF NOT EXISTS idx_iam_refresh_token_subject
    ON iam_refresh_token (subject);

CREATE INDEX IF NOT EXISTS idx_iam_refresh_token_expires_at
    ON iam_refresh_token (expires_at);

CREATE INDEX IF NOT EXISTS idx_iam_refresh_token_revoked_at
    ON iam_refresh_token (revoked_at);

CREATE INDEX IF NOT EXISTS idx_iam_login_failure_locked_until
    ON iam_login_failure (locked_until);

CREATE INDEX IF NOT EXISTS idx_iam_login_failure_expires_at
    ON iam_login_failure (expires_at);

CREATE INDEX IF NOT EXISTS idx_iam_captcha_challenge_expires_at
    ON iam_captcha_challenge (expires_at);

CREATE INDEX IF NOT EXISTS idx_iam_oidc_state_expires_at
    ON iam_oidc_state (expires_at);

CREATE INDEX IF NOT EXISTS idx_iam_external_identity_user_id
    ON iam_external_identity (user_id);

CREATE UNIQUE INDEX IF NOT EXISTS idx_iam_external_identity_provider_subject
    ON iam_external_identity (provider, subject);

INSERT INTO iam_user (
    username,
    nickname,
    password,
    email,
    phone,
    avatar,
    status,
    created_at,
    updated_at
)
SELECT
    'admin',
    'admin',
    '$2a$12$ped6ldtK7wf2vUg8049AOe.8OxkwBnguQ0E4ttgpUlh.pESkt9fkq',
    '',
    '',
    '',
    1,
    NOW(),
    NOW()
WHERE NOT EXISTS (
    SELECT 1
    FROM iam_user
    WHERE username = 'admin'
      AND deleted_at IS NULL
);
