ALTER TABLE IF EXISTS iam_users
    ADD COLUMN IF NOT EXISTS mfa_enabled BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS mfa_secret VARCHAR(512) NOT NULL DEFAULT '';

ALTER TABLE IF EXISTS iam_users
    ALTER COLUMN mfa_secret TYPE VARCHAR(512);

CREATE TABLE IF NOT EXISTS iam_auth_sessions (
    id VARCHAR(64) PRIMARY KEY,
    subject VARCHAR(128) NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    revoked_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS iam_revoked_tokens (
    id VARCHAR(64) PRIMARY KEY,
    expires_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS iam_refresh_tokens (
    id VARCHAR(64) PRIMARY KEY,
    session_id VARCHAR(64) NOT NULL,
    subject VARCHAR(128) NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    revoked_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS iam_login_failures (
    key VARCHAR(256) PRIMARY KEY,
    count INTEGER NOT NULL,
    locked_until TIMESTAMPTZ NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS iam_captcha_challenges (
    id VARCHAR(128) PRIMARY KEY,
    digits BYTEA NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS iam_oidc_states (
    state VARCHAR(128) PRIMARY KEY,
    expires_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS iam_external_identities (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    provider VARCHAR(255) NOT NULL,
    subject VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL DEFAULT '',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_iam_auth_sessions_subject
    ON iam_auth_sessions (subject);

CREATE INDEX IF NOT EXISTS idx_iam_auth_sessions_expires_at
    ON iam_auth_sessions (expires_at);

CREATE INDEX IF NOT EXISTS idx_iam_auth_sessions_revoked_at
    ON iam_auth_sessions (revoked_at);

CREATE INDEX IF NOT EXISTS idx_iam_revoked_tokens_expires_at
    ON iam_revoked_tokens (expires_at);

CREATE INDEX IF NOT EXISTS idx_iam_refresh_tokens_session_id
    ON iam_refresh_tokens (session_id);

CREATE INDEX IF NOT EXISTS idx_iam_refresh_tokens_subject
    ON iam_refresh_tokens (subject);

CREATE INDEX IF NOT EXISTS idx_iam_refresh_tokens_expires_at
    ON iam_refresh_tokens (expires_at);

CREATE INDEX IF NOT EXISTS idx_iam_refresh_tokens_revoked_at
    ON iam_refresh_tokens (revoked_at);

CREATE INDEX IF NOT EXISTS idx_iam_login_failures_locked_until
    ON iam_login_failures (locked_until);

CREATE INDEX IF NOT EXISTS idx_iam_login_failures_expires_at
    ON iam_login_failures (expires_at);

CREATE INDEX IF NOT EXISTS idx_iam_captcha_challenges_expires_at
    ON iam_captcha_challenges (expires_at);

CREATE INDEX IF NOT EXISTS idx_iam_oidc_states_expires_at
    ON iam_oidc_states (expires_at);

CREATE INDEX IF NOT EXISTS idx_iam_external_identities_user_id
    ON iam_external_identities (user_id);

CREATE UNIQUE INDEX IF NOT EXISTS idx_iam_external_identities_provider_subject
    ON iam_external_identities (provider, subject);

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'fk_iam_external_identities_user'
    ) THEN
        DELETE FROM iam_external_identities identities
        WHERE NOT EXISTS (
            SELECT 1
            FROM iam_users users
            WHERE users.id = identities.user_id
        );

        ALTER TABLE iam_external_identities
            ADD CONSTRAINT fk_iam_external_identities_user
            FOREIGN KEY (user_id) REFERENCES iam_users(id) ON DELETE CASCADE
            NOT VALID;

        ALTER TABLE iam_external_identities
            VALIDATE CONSTRAINT fk_iam_external_identities_user;
    END IF;
END $$;
