ALTER TABLE IF EXISTS iam_users RENAME TO iam_users_legacy;

CREATE TABLE IF NOT EXISTS iam_users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    legacy_id VARCHAR(32),
    username VARCHAR(64) NOT NULL,
    nickname VARCHAR(64) NOT NULL,
    password VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL DEFAULT '',
    phone VARCHAR(32) NOT NULL DEFAULT '',
    avatar VARCHAR(512) NOT NULL DEFAULT '',
    remarks VARCHAR(512) NOT NULL DEFAULT '',
    is_admin BOOLEAN NOT NULL DEFAULT FALSE,
    status SMALLINT NOT NULL DEFAULT 1,
    roles TEXT NOT NULL DEFAULT 'user',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    deleted_at TIMESTAMPTZ
);

DO $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM information_schema.tables
        WHERE table_schema = 'public' AND table_name = 'iam_users_legacy'
    ) THEN
        INSERT INTO iam_users (legacy_id, username, nickname, password, email, phone, avatar, remarks, is_admin, status, roles, created_at, updated_at, deleted_at)
        SELECT
            id AS legacy_id,
            CASE
                WHEN COALESCE(NULLIF(BTRIM(email), ''), '') <> '' THEN LOWER(BTRIM(email))
                ELSE 'legacy_user_' || ROW_NUMBER() OVER (ORDER BY created_at, updated_at)
            END AS username,
            COALESCE(NULLIF(BTRIM(name), ''), 'legacy user') AS nickname,
            '' AS password,
            LOWER(COALESCE(BTRIM(email), '')) AS email,
            '' AS phone,
            '' AS avatar,
            '' AS remarks,
            EXISTS (
                SELECT 1
                FROM unnest(string_to_array(COALESCE(roles, ''), ',')) AS role_item
                WHERE LOWER(BTRIM(role_item)) = 'admin'
            ) AS is_admin,
            1 AS status,
            COALESCE(NULLIF(BTRIM(roles), ''), 'user') AS roles,
            created_at,
            updated_at,
            deleted_at
        FROM iam_users_legacy;

        DROP TABLE iam_users_legacy;
    END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_iam_users_deleted_at
    ON iam_users (deleted_at);

CREATE UNIQUE INDEX IF NOT EXISTS idx_iam_users_legacy_id_active
    ON iam_users (legacy_id)
    WHERE deleted_at IS NULL AND legacy_id IS NOT NULL AND legacy_id <> '';

CREATE UNIQUE INDEX IF NOT EXISTS idx_iam_users_username_active
    ON iam_users (username)
    WHERE deleted_at IS NULL;

CREATE UNIQUE INDEX IF NOT EXISTS idx_iam_users_email_active
    ON iam_users (email)
    WHERE deleted_at IS NULL AND email <> '';
